/*
 * guest-os/apps/amba-virt-demo/DashboardHtml.hxx
 *
 * Ambarella Virtualization Demo Hub - Live HTML5 Dashboard Asset
 * Copyright (C) 2026, Ambarella International LLC.
 */

#ifndef AMBA_VIRT_DASHBOARD_HTML_HXX
#define AMBA_VIRT_DASHBOARD_HTML_HXX

static const char *HTML_TEMPLATE =
"<!DOCTYPE html>\n"
"<html lang=\"en\">\n"
"<head>\n"
"  <meta charset=\"UTF-8\">\n"
"  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
"  <title>Ambarella Virtualization Demo Hub</title>\n"
"  <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\n"
"  <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\n"
"  <link href=\"https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;500;600;700&family=JetBrains+Mono:wght@400;500;600&display=swap\" rel=\"stylesheet\">\n"
"  <style>\n"
"    :root {\n"
"      --bg-base: #0a0d14;\n"
"      --bg-surface: #111726;\n"
"      --bg-card: rgba(19, 27, 46, 0.75);\n"
"      --border: rgba(255, 255, 255, 0.08);\n"
"      --border-focus: rgba(0, 229, 255, 0.4);\n"
"      --accent: #00e5ff;\n"
"      --accent-glow: rgba(0, 229, 255, 0.25);\n"
"      --emerald: #10b981;\n"
"      --amber: #f59e0b;\n"
"      --rose: #f43f5e;\n"
"      --text-main: #f8fafc;\n"
"      --text-sub: #94a3b8;\n"
"    }\n"
"    * { box-sizing: border-box; margin: 0; padding: 0; }\n"
"    body {\n"
"      background: var(--bg-base);\n"
"      color: var(--text-main);\n"
"      font-family: 'Outfit', -apple-system, sans-serif;\n"
"      min-height: 100vh;\n"
"      display: flex;\n"
"      flex-direction: column;\n"
"      background-image: radial-gradient(circle at 50% 0%, rgba(0, 229, 255, 0.07), transparent 50%),\n"
"                        radial-gradient(circle at 100% 100%, rgba(16, 185, 129, 0.05), transparent 40%);\n"
"    }\n"
"    header {\n"
"      background: rgba(17, 23, 38, 0.85);\n"
"      backdrop-filter: blur(12px);\n"
"      border-bottom: 1px solid var(--border);\n"
"      padding: 1rem 2rem;\n"
"      display: flex;\n"
"      justify-content: space-between;\n"
"      align-items: center;\n"
"      position: sticky;\n"
"      top: 0;\n"
"      z-index: 100;\n"
"    }\n"
"    .logo-group { display: flex; align-items: center; gap: 1rem; }\n"
"    .brand { font-size: 1.25rem; font-weight: 700; letter-spacing: -0.02em; color: #fff; }\n"
"    .brand span { color: var(--accent); }\n"
"    .os-badge {\n"
"      display: inline-flex;\n"
"      align-items: center;\n"
"      gap: 0.5rem;\n"
"      padding: 0.35rem 0.85rem;\n"
"      border-radius: 9999px;\n"
"      font-size: 0.82rem;\n"
"      font-weight: 600;\n"
"      background: rgba(16, 185, 129, 0.12);\n"
"      border: 1px solid rgba(16, 185, 129, 0.35);\n"
"      color: #34d399;\n"
"    }\n"
"    .pulse-dot {\n"
"      width: 8px; height: 8px; border-radius: 50%;\n"
"      background: var(--emerald);\n"
"      box-shadow: 0 0 10px var(--emerald);\n"
"      animation: pulse 2s infinite;\n"
"    }\n"
"    .pulse-dot.paused {\n"
"      background: var(--amber);\n"
"      box-shadow: 0 0 10px var(--amber);\n"
"      animation: none;\n"
"    }\n"
"    @keyframes pulse { 0%, 100% { opacity: 1; transform: scale(1); } 50% { opacity: 0.4; transform: scale(0.85); } }\n"
"\n"
"    /* Nav Tabs */\n"
"    .tab-bar {\n"
"      display: flex;\n"
"      gap: 0.5rem;\n"
"      background: rgba(0, 0, 0, 0.3);\n"
"      padding: 0.25rem;\n"
"      border-radius: 10px;\n"
"      border: 1px solid var(--border);\n"
"    }\n"
"    .tab-btn {\n"
"      background: transparent;\n"
"      border: none;\n"
"      color: var(--text-sub);\n"
"      padding: 0.5rem 1.2rem;\n"
"      border-radius: 7px;\n"
"      font-size: 0.88rem;\n"
"      font-weight: 600;\n"
"      cursor: pointer;\n"
"      transition: all 0.2s ease;\n"
"      display: flex;\n"
"      align-items: center;\n"
"      gap: 0.5rem;\n"
"    }\n"
"    .tab-btn:hover { color: #fff; }\n"
"    .tab-btn.active {\n"
"      background: var(--accent);\n"
"      color: #050b14;\n"
"      box-shadow: 0 0 15px var(--accent-glow);\n"
"    }\n"
"\n"
"    main {\n"
"      flex: 1;\n"
"      max-width: 1440px;\n"
"      margin: 0 auto;\n"
"      width: 100%;\n"
"      padding: 1.75rem 2rem;\n"
"      display: grid;\n"
"      grid-template-columns: 360px 1fr;\n"
"      gap: 1.75rem;\n"
"    }\n"
"\n"
"    .card {\n"
"      background: var(--bg-card);\n"
"      backdrop-filter: blur(12px);\n"
"      border: 1px solid var(--border);\n"
"      border-radius: 16px;\n"
"      padding: 1.5rem;\n"
"      display: flex;\n"
"      flex-direction: column;\n"
"      gap: 1.25rem;\n"
"      box-shadow: 0 8px 32px rgba(0, 0, 0, 0.37);\n"
"    }\n"
"    .card-title {\n"
"      font-size: 0.95rem;\n"
"      font-weight: 600;\n"
"      text-transform: uppercase;\n"
"      letter-spacing: 0.05em;\n"
"      color: var(--text-sub);\n"
"      display: flex;\n"
"      align-items: center;\n"
"      justify-content: space-between;\n"
"    }\n"
"\n"
"    /* Stats Grid */\n"
"    .stats-grid {\n"
"      display: grid;\n"
"      grid-template-columns: 1fr 1fr;\n"
"      gap: 0.85rem;\n"
"    }\n"
"    .stat-box {\n"
"      background: rgba(13, 19, 33, 0.6);\n"
"      border: 1px solid var(--border);\n"
"      border-radius: 12px;\n"
"      padding: 1rem;\n"
"      display: flex;\n"
"      flex-direction: column;\n"
"      gap: 0.35rem;\n"
"    }\n"
"    .stat-label {\n"
"      font-size: 0.75rem;\n"
"      color: var(--text-sub);\n"
"      text-transform: uppercase;\n"
"      letter-spacing: 0.05em;\n"
"    }\n"
"    .stat-val {\n"
"      font-family: 'JetBrains Mono', monospace;\n"
"      font-size: 1.35rem;\n"
"      font-weight: 600;\n"
"      color: #fff;\n"
"    }\n"
"    .stat-val.accent { color: var(--accent); }\n"
"    .stat-val.emerald { color: #34d399; }\n"
"\n"
"    /* Sliders and Controls */\n"
"    .control-group {\n"
"      display: flex;\n"
"      flex-direction: column;\n"
"      gap: 0.5rem;\n"
"    }\n"
"    .control-label {\n"
"      font-size: 0.82rem;\n"
"      font-weight: 500;\n"
"      color: var(--text-sub);\n"
"      display: flex;\n"
"      justify-content: space-between;\n"
"    }\n"
"    .control-label span {\n"
"      font-family: 'JetBrains Mono', monospace;\n"
"      color: var(--accent);\n"
"    }\n"
"    input[type=range] {\n"
"      -webkit-appearance: none;\n"
"      appearance: none;\n"
"      width: 100%;\n"
"      height: 6px;\n"
"      background: #1e293b;\n"
"      border-radius: 4px;\n"
"      outline: none;\n"
"    }\n"
"    input[type=range]::-webkit-slider-thumb {\n"
"      -webkit-appearance: none;\n"
"      appearance: none;\n"
"      width: 16px;\n"
"      height: 16px;\n"
"      border-radius: 50%;\n"
"      background: var(--accent);\n"
"      cursor: pointer;\n"
"      box-shadow: 0 0 10px var(--accent-glow);\n"
"      transition: transform 0.1s;\n"
"    }\n"
"    input[type=range]::-webkit-slider-thumb:hover { transform: scale(1.2); }\n"
"\n"
"    .btn-action {\n"
"      background: linear-gradient(135deg, #00e5ff, #0099ff);\n"
"      color: #040914;\n"
"      border: none;\n"
"      padding: 0.85rem;\n"
"      border-radius: 10px;\n"
"      font-size: 0.95rem;\n"
"      font-weight: 700;\n"
"      cursor: pointer;\n"
"      transition: all 0.2s ease;\n"
"      display: flex;\n"
"      align-items: center;\n"
"      justify-content: center;\n"
"      gap: 0.5rem;\n"
"    }\n"
"    .btn-action:hover {\n"
"      transform: translateY(-2px);\n"
"      box-shadow: 0 4px 20px var(--accent-glow);\n"
"    }\n"
"    .btn-secondary {\n"
"      background: rgba(255, 255, 255, 0.05);\n"
"      color: var(--text-main);\n"
"      border: 1px solid var(--border);\n"
"      padding: 0.65rem 1rem;\n"
"      border-radius: 8px;\n"
"      font-size: 0.85rem;\n"
"      font-weight: 600;\n"
"      cursor: pointer;\n"
"      display: flex;\n"
"      align-items: center;\n"
"      gap: 0.5rem;\n"
"      transition: background 0.2s;\n"
"    }\n"
"    .btn-secondary:hover { background: rgba(255, 255, 255, 0.1); }\n"
"\n"
"    /* Detection List */\n"
"    .det-list {\n"
"      display: flex;\n"
"      flex-direction: column;\n"
"      gap: 0.5rem;\n"
"      max-height: 220px;\n"
"      overflow-y: auto;\n"
"      padding-right: 4px;\n"
"    }\n"
"    .det-list::-webkit-scrollbar { width: 4px; }\n"
"    .det-list::-webkit-scrollbar-thumb { background: rgba(255, 255, 255, 0.1); border-radius: 4px; }\n"
"    .det-item {\n"
"      background: rgba(13, 19, 33, 0.5);\n"
"      border: 1px solid var(--border);\n"
"      border-radius: 8px;\n"
"      padding: 0.5rem 0.75rem;\n"
"      display: flex;\n"
"      justify-content: space-between;\n"
"      align-items: center;\n"
"      font-size: 0.85rem;\n"
"    }\n"
"    .det-tag {\n"
"      font-family: 'JetBrains Mono', monospace;\n"
"      font-size: 0.75rem;\n"
"      padding: 0.2rem 0.5rem;\n"
"      border-radius: 4px;\n"
"      font-weight: 600;\n"
"    }\n"
"\n"
"    /* Viewport Area */\n"
"    .viewport-card {\n"
"      background: var(--bg-card);\n"
"      border: 1px solid var(--border);\n"
"      border-radius: 16px;\n"
"      padding: 1.5rem;\n"
"      display: flex;\n"
"      flex-direction: column;\n"
"      gap: 1rem;\n"
"      min-height: 600px;\n"
"    }\n"
"    .viewport-header {\n"
"      display: flex;\n"
"      justify-content: space-between;\n"
"      align-items: center;\n"
"    }\n"
"    .canvas-container {\n"
"      flex: 1;\n"
"      background: #030712;\n"
"      border: 1px solid var(--border);\n"
"      border-radius: 12px;\n"
"      position: relative;\n"
"      overflow: hidden;\n"
"      display: flex;\n"
"      align-items: center;\n"
"      justify-content: center;\n"
"    }\n"
"    #liveCanvas {\n"
"      max-width: 100%;\n"
"      max-height: 100%;\n"
"      display: block;\n"
"      border-radius: 8px;\n"
"      box-shadow: 0 4px 20px rgba(0,0,0,0.5);\n"
"    }\n"
"\n"
"    /* Photo Upload Elements */\n"
"    .upload-zone {\n"
"      border: 2px dashed rgba(255, 255, 255, 0.15);\n"
"      border-radius: 12px;\n"
"      height: 100%;\n"
"      width: 100%;\n"
"      display: flex;\n"
"      flex-direction: column;\n"
"      align-items: center;\n"
"      justify-content: center;\n"
"      gap: 1rem;\n"
"      cursor: pointer;\n"
"      transition: all 0.2s ease;\n"
"      background: rgba(13, 19, 33, 0.3);\n"
"      padding: 2rem;\n"
"    }\n"
"    .upload-zone.dragover, .upload-zone:hover {\n"
"      border-color: var(--accent);\n"
"      background: rgba(0, 229, 255, 0.05);\n"
"    }\n"
"    #uploadCanvas {\n"
"      max-width: 100%;\n"
"      max-height: 520px;\n"
"      object-fit: contain;\n"
"      border-radius: 8px;\n"
"      display: none;\n"
"    }\n"
"\n"
"    footer {\n"
"      padding: 1rem 2rem;\n"
"      border-top: 1px solid var(--border);\n"
"      font-size: 0.78rem;\n"
"      color: var(--text-sub);\n"
"      display: flex;\n"
"      justify-content: space-between;\n"
"      background: rgba(11, 16, 28, 0.5);\n"
"    }\n"
"  </style>\n"
"</head>\n"
"<body>\n"
"\n"
"  <header>\n"
"    <div class=\"logo-group\">\n"
"      <div class=\"brand\">Ambarella <span>Virtualization</span> Demo Hub</div>\n"
"      <div class=\"os-badge\">\n"
"        <div id=\"statusDot\" class=\"pulse-dot\"></div>\n"
"        <span id=\"osBadgeText\">Connecting to Ambarella N1-655...</span>\n"
"      </div>\n"
"    </div>\n"
"\n"
"    <div class=\"tab-bar\">\n"
"      <button id=\"tabLiveBtn\" class=\"tab-btn active\">\n"
"        <svg width=\"16\" height=\"16\" fill=\"currentColor\" viewBox=\"0 0 24 24\"><path d=\"M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm-1 14.5v-9l6 4.5-6 4.5z\"/></svg>\n"
"        Live Camera Stream\n"
"      </button>\n"
"      <button id=\"tabUploadBtn\" class=\"tab-btn\">\n"
"        <svg width=\"16\" height=\"16\" fill=\"currentColor\" viewBox=\"0 0 24 24\"><path d=\"M19.35 10.04C18.67 6.59 15.64 4 12 4 9.11 4 6.6 5.64 5.35 8.04 2.34 8.36 0 10.91 0 14c0 3.31 2.69 6 6 6h13c2.76 0 5-2.24 5-5 0-2.64-2.05-4.78-4.65-4.96zM14 13v4h-4v-4H7l5-5 5 5h-3z\"/></svg>\n"
"        Photo Upload\n"
"      </button>\n"
"    </div>\n"
"  </header>\n"
"\n"
"  <main>\n"
"    <!-- Left Column: Controls & Telemetry -->\n"
"    <div class=\"card\">\n"
"      <div class=\"card-title\">\n"
"        <span>Hardware Telemetry</span>\n"
"        <span id=\"streamStateBadge\" class=\"det-tag\" style=\"background:rgba(0,229,255,0.1); color:var(--accent);\">STANDBY</span>\n"
"      </div>\n"
"\n"
"      <div class=\"stats-grid\">\n"
"        <div class=\"stat-box\">\n"
"          <div class=\"stat-label\">VisORC Execution</div>\n"
"          <div id=\"statVisorcMs\" class=\"stat-val accent\">--</div>\n"
"        </div>\n"
"        <div class=\"stat-box\">\n"
"          <div class=\"stat-label\">In-Guest Total</div>\n"
"          <div id=\"statTotalMs\" class=\"stat-val emerald\">--</div>\n"
"        </div>\n"
"        <div class=\"stat-box\">\n"
"          <div class=\"stat-label\">Stream FPS</div>\n"
"          <div id=\"statFps\" class=\"stat-val\">--</div>\n"
"        </div>\n"
"        <div class=\"stat-box\">\n"
"          <div class=\"stat-label\">Active Detections</div>\n"
"          <div id=\"statCount\" class=\"stat-val\">0</div>\n"
"        </div>\n"
"      </div>\n"
"\n"
"      <div class=\"card-title\" style=\"margin-top:0.5rem;\">Inference Parameters</div>\n"
"\n"
"      <div class=\"control-group\">\n"
"        <div class=\"control-label\">\n"
"          <span>Confidence Filter</span>\n"
"          <span id=\"threshVal\">0.25</span>\n"
"        </div>\n"
"        <input type=\"range\" id=\"threshSlider\" min=\"0.05\" max=\"0.95\" step=\"0.05\" value=\"0.25\">\n"
"      </div>\n"
"\n"
"      <div class=\"control-group\">\n"
"        <div class=\"control-label\">\n"
"          <span>NMS IoU Threshold</span>\n"
"          <span id=\"nmsVal\">0.45</span>\n"
"        </div>\n"
"        <input type=\"range\" id=\"nmsSlider\" min=\"0.10\" max=\"0.90\" step=\"0.05\" value=\"0.45\">\n"
"      </div>\n"
"\n"
"      <div id=\"uploadControls\" style=\"display:none; flex-direction:column; gap:0.75rem;\">\n"
"        <button id=\"inferBtn\" class=\"btn-action\">Run VisORC Inference</button>\n"
"      </div>\n"
"\n"
"      <div class=\"card-title\" style=\"margin-top:0.5rem;\">Detected Objects</div>\n"
"      <div id=\"detList\" class=\"det-list\">\n"
"        <div style=\"text-align: center; color: var(--text-sub); font-size: 0.85rem; padding: 1rem;\">\n"
"          No active detections\n"
"        </div>\n"
"      </div>\n"
"    </div>\n"
"\n"
"    <!-- Right Column: Viewport -->\n"
"    <div class=\"viewport-card\">\n"
"      <div class=\"viewport-header\">\n"
"        <div style=\"font-weight:600; font-size:1.05rem;\" id=\"viewportTitle\">Live Sensor Viewport (Clean JPEG + VisORC Overlay)</div>\n"
"        <div style=\"display:flex; gap:0.5rem;\">\n"
"          <button id=\"pauseBtn\" class=\"btn-secondary\">\n"
"            <svg id=\"pauseIcon\" width=\"14\" height=\"14\" fill=\"currentColor\" viewBox=\"0 0 24 24\"><path d=\"M6 19h4V5H6v14zm8-14v14h4V5h-4z\"/></svg>\n"
"            <span id=\"pauseBtnText\">Pause</span>\n"
"          </button>\n"
"        </div>\n"
"      </div>\n"
"\n"
"      <div class=\"canvas-container\">\n"
"        <!-- Live Stream Canvas -->\n"
"        <canvas id=\"liveCanvas\" width=\"640\" height=\"360\"></canvas>\n"
"\n"
"        <!-- Photo Upload Dropzone (shown on tab switch) -->\n"
"        <div id=\"uploadZone\" class=\"upload-zone\" style=\"display:none;\">\n"
"          <svg width=\"48\" height=\"48\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.5\" viewBox=\"0 0 24 24\" style=\"color:var(--text-sub);\">\n"
"            <path stroke-linecap=\"round\" stroke-linejoin=\"round\" d=\"M12 16.5V9.75m0 0l3 3m-3-3l-3 3M6.75 19.5a4.5 4.5 0 01-1.41-8.775 5.25 5.25 0 0110.233-2.33 3 3 0 013.758 3.848A3.752 3.752 0 0118 19.5H6.75z\" />\n"
"          </svg>\n"
"          <div style=\"text-align:center;\">\n"
"            <div style=\"font-weight:600; font-size:1rem; margin-bottom:0.25rem;\">Drop image here or click to browse</div>\n"
"            <div style=\"font-size:0.8rem; color:var(--text-sub);\">JPEG, PNG supported (Processed by VisORC hardware)</div>\n"
"          </div>\n"
"          <input type=\"file\" id=\"fileInput\" accept=\"image/*\" style=\"display:none;\">\n"
"          <canvas id=\"uploadCanvas\"></canvas>\n"
"        </div>\n"
"      </div>\n"
"    </div>\n"
"  </main>\n"
"\n"
"  <footer>\n"
"    <div>Ambarella International LLC &mdash; N1-655 VisORC Neural Virtualization Engine</div>\n"
"    <div id=\"footerStatus\">Protocol: Nanopb v1 RPC | Clean JPEG Ping-Pong Architecture</div>\n"
"  </footer>\n"
"\n"
"  <script>\n"
"    /* Color Palette for 10 distinct classes */\n"
"    const CLASS_COLORS = [\n"
"      { border: 'rgb(59, 130, 246)', bg: 'rgba(59, 130, 246, 0.15)' },\n"
"      { border: 'rgb(16, 185, 129)', bg: 'rgba(16, 185, 129, 0.15)' },\n"
"      { border: 'rgb(245, 158, 11)',  bg: 'rgba(245, 158, 11, 0.15)' },\n"
"      { border: 'rgb(239, 68, 68)',   bg: 'rgba(239, 68, 68, 0.15)' },\n"
"      { border: 'rgb(168, 85, 247)', bg: 'rgba(168, 85, 247, 0.15)' },\n"
"      { border: 'rgb(236, 72, 153)', bg: 'rgba(236, 72, 153, 0.15)' },\n"
"      { border: 'rgb(6, 182, 212)',  bg: 'rgba(6, 182, 212, 0.15)' },\n"
"      { border: 'rgb(132, 204, 22)', bg: 'rgba(132, 204, 22, 0.15)' },\n"
"      { border: 'rgb(249, 115, 22)', bg: 'rgba(249, 115, 22, 0.15)' },\n"
"      { border: 'rgb(147, 51, 234)', bg: 'rgba(147, 51, 234, 0.15)' }\n"
"    ];\n"
"\n"
"    let activeTab = 'live';\n"
"    let streamAbort = null;\n"
"    let streamPaused = false;\n"
"    let currentConf = 0.25;\n"
"    let currentNms = 0.45;\n"
"\n"
"    // DOM Elements\n"
"    const tabLiveBtn = document.getElementById('tabLiveBtn');\n"
"    const tabUploadBtn = document.getElementById('tabUploadBtn');\n"
"    const liveCanvas = document.getElementById('liveCanvas');\n"
"    const ctx = liveCanvas.getContext('2d');\n"
"    const uploadZone = document.getElementById('uploadZone');\n"
"    const uploadControls = document.getElementById('uploadControls');\n"
"    const viewportTitle = document.getElementById('viewportTitle');\n"
"    const pauseBtn = document.getElementById('pauseBtn');\n"
"    const pauseBtnText = document.getElementById('pauseBtnText');\n"
"    const pauseIcon = document.getElementById('pauseIcon');\n"
"    const statusDot = document.getElementById('statusDot');\n"
"    const streamStateBadge = document.getElementById('streamStateBadge');\n"
"    const threshSlider = document.getElementById('threshSlider');\n"
"    const threshVal = document.getElementById('threshVal');\n"
"    const nmsSlider = document.getElementById('nmsSlider');\n"
"    const nmsVal = document.getElementById('nmsVal');\n"
"    const detList = document.getElementById('detList');\n"
"    const fileInput = document.getElementById('fileInput');\n"
"    const uploadCanvas = document.getElementById('uploadCanvas');\n"
"    const uploadCtx = uploadCanvas.getContext('2d');\n"
"    let loadedImage = null;\n"
"    const inferBtn = document.getElementById('inferBtn');\n"
"\n"
"    // Tab Switching\n"
"    tabLiveBtn.onclick = () => switchTab('live');\n"
"    tabUploadBtn.onclick = () => switchTab('upload');\n"
"\n"
"    function switchTab(tab) {\n"
"      if (activeTab === tab) return;\n"
"      activeTab = tab;\n"
"\n"
"      if (tab === 'live') {\n"
"        tabLiveBtn.classList.add('active');\n"
"        tabUploadBtn.classList.remove('active');\n"
"        liveCanvas.style.display = 'block';\n"
"        uploadZone.style.display = 'none';\n"
"        uploadControls.style.display = 'none';\n"
"        pauseBtn.style.display = 'flex';\n"
"        viewportTitle.innerText = 'Live Sensor Viewport (Clean JPEG + VisORC Overlay)';\n"
"        startStream();\n"
"      } else {\n"
"        tabUploadBtn.classList.add('active');\n"
"        tabLiveBtn.classList.remove('active');\n"
"        liveCanvas.style.display = 'none';\n"
"        uploadZone.style.display = 'flex';\n"
"        uploadControls.style.display = 'flex';\n"
"        pauseBtn.style.display = 'none';\n"
"        viewportTitle.innerText = 'Photo Upload & Static Inspection';\n"
"        stopStream();\n"
"      }\n"
"    }\n"
"\n"
"    // Play / Pause Toggle\n"
"    pauseBtn.onclick = () => {\n"
"      streamPaused = !streamPaused;\n"
"      if (streamPaused) {\n"
"        stopStream();\n"
"        pauseBtnText.innerText = 'Resume';\n"
"        pauseIcon.innerHTML = '<path d=\"M8 5v14l11-7z\"/>';\n"
"        statusDot.classList.add('paused');\n"
"        streamStateBadge.innerText = 'PAUSED';\n"
"        streamStateBadge.style.color = 'var(--amber)';\n"
"      } else {\n"
"        startStream();\n"
"        pauseBtnText.innerText = 'Pause';\n"
"        pauseIcon.innerHTML = '<path d=\"M6 19h4V5H6v14zm8-14v14h4V5h-4z\"/>';\n"
"        statusDot.classList.remove('paused');\n"
"        streamStateBadge.innerText = 'STREAMING';\n"
"        streamStateBadge.style.color = 'var(--accent)';\n"
"      }\n"
"    };\n"
"\n"
"    // Sliders\n"
"    threshSlider.oninput = () => {\n"
"      currentConf = parseFloat(threshSlider.value);\n"
"      threshVal.innerText = currentConf.toFixed(2);\n"
"    };\n"
"\n"
"    nmsSlider.oninput = () => {\n"
"      currentNms = parseFloat(nmsSlider.value);\n"
"      nmsVal.innerText = currentNms.toFixed(2);\n"
"    };\n"
"\n"
"    nmsSlider.onchange = async () => {\n"
"      try {\n"
"        await fetch('/live/params', {\n"
"          method: 'POST',\n"
"          headers: { 'Content-Type': 'application/json' },\n"
"          body: JSON.stringify({ nms: currentNms, conf: currentConf })\n"
"        });\n"
"      } catch (e) {\n"
"        console.error('Failed to update live params:', e);\n"
"      }\n"
"    };\n"
"\n"
"    // Page Visibility API: Auto-pause stream when tab is hidden\n"
"    document.addEventListener('visibilitychange', () => {\n"
"      if (document.visibilityState === 'hidden') {\n"
"        if (activeTab === 'live' && !streamPaused) {\n"
"          stopStream();\n"
"        }\n"
"      } else {\n"
"        if (activeTab === 'live' && !streamPaused) {\n"
"          startStream();\n"
"        }\n"
"      }\n"
"    });\n"
"\n"
"    // Stream Reader: GET /live/stream\n"
"    async function startStream() {\n"
"      if (streamAbort) {\n"
"        streamAbort.abort();\n"
"      }\n"
"      streamAbort = new AbortController();\n"
"      const signal = streamAbort.signal;\n"
"\n"
"      streamStateBadge.innerText = 'CONNECTING';\n"
"      streamStateBadge.style.color = 'var(--accent)';\n"
"\n"
"      try {\n"
"        const res = await fetch('/live/stream', { signal });\n"
"        if (!res.ok) throw new Error(`HTTP ${res.status}`);\n"
"\n"
"        streamStateBadge.innerText = 'STREAMING';\n"
"        streamStateBadge.style.color = '#34d399';\n"
"        statusDot.classList.remove('paused');\n"
"\n"
"        const reader = res.body.getReader();\n"
"        let chunkBuf = new Uint8Array(0);\n"
"\n"
"        while (true) {\n"
"          const { done, value } = await reader.read();\n"
"          if (done) break;\n"
"\n"
"          // Append incoming chunk\n"
"          const nextBuf = new Uint8Array(chunkBuf.length + value.length);\n"
"          nextBuf.set(chunkBuf, 0);\n"
"          nextBuf.set(value, chunkBuf.length);\n"
"          chunkBuf = nextBuf;\n"
"\n"
"          // Process complete frames in buffer\n"
"          while (chunkBuf.length >= 8) {\n"
"            const view = new DataView(chunkBuf.buffer, chunkBuf.byteOffset, chunkBuf.byteLength);\n"
"            const jsonLen = view.getUint32(0, true);\n"
"            const jpegLen = view.getUint32(4, true);\n"
"            const totalFrameLen = 8 + jsonLen + jpegLen;\n"
"\n"
"            if (chunkBuf.length < totalFrameLen) {\n"
"              // Wait for remaining frame bytes\n"
"              break;\n"
"            }\n"
"\n"
"            // Extract JSON and JPEG slices\n"
"            const jsonBytes = chunkBuf.subarray(8, 8 + jsonLen);\n"
"            const jpegBytes = chunkBuf.subarray(8 + jsonLen, totalFrameLen);\n"
"            chunkBuf = chunkBuf.subarray(totalFrameLen);\n"
"\n"
"            try {\n"
"              const jsonStr = new TextDecoder('utf-8').decode(jsonBytes);\n"
"              const meta = JSON.parse(jsonStr);\n"
"              renderFrame(meta, jpegBytes);\n"
"            } catch (err) {\n"
"              console.error('Frame decode error:', err);\n"
"            }\n"
"          }\n"
"        }\n"
"      } catch (err) {\n"
"        if (err.name !== 'AbortError') {\n"
"          console.warn('Live stream disconnected:', err.message);\n"
"          streamStateBadge.innerText = 'DISCONNECTED';\n"
"          streamStateBadge.style.color = 'var(--rose)';\n"
"        }\n"
"      }\n"
"    }\n"
"\n"
"    function stopStream() {\n"
"      if (streamAbort) {\n"
"        streamAbort.abort();\n"
"        streamAbort = null;\n"
"      }\n"
"      streamStateBadge.innerText = 'SLEEPING';\n"
"      streamStateBadge.style.color = 'var(--amber)';\n"
"    }\n"
"\n"
"    // Single Canvas Drawing: Render JPEG then overlay bounding boxes\n"
"    async function renderFrame(meta, jpegBytes) {\n"
"      const blob = new Blob([jpegBytes], { type: 'image/jpeg' });\n"
"      let bmp = null;\n"
"      try {\n"
"        bmp = await createImageBitmap(blob);\n"
"      } catch (e) {\n"
"        // Fallback for environments lacking createImageBitmap\n"
"        bmp = await new Promise((resolve, reject) => {\n"
"          const img = new Image();\n"
"          img.onload = () => resolve(img);\n"
"          img.onerror = reject;\n"
"          img.src = URL.createObjectURL(blob);\n"
"        });\n"
"      }\n"
"\n"
"      if (liveCanvas.width !== bmp.width || liveCanvas.height !== bmp.height) {\n"
"        liveCanvas.width = bmp.width;\n"
"        liveCanvas.height = bmp.height;\n"
"      }\n"
"\n"
"      // 1. Draw clean JPEG\n"
"      ctx.drawImage(bmp, 0, 0);\n"
"\n"
"      // 2. Filter detections by client-side confidence slider\n"
"      const dets = (meta.detections || []).filter(d => d.confidence >= currentConf);\n"
"\n"
"      // 3. Draw bounding boxes and class tags\n"
"      dets.forEach((d, idx) => {\n"
"        const sx = liveCanvas.width;\n"
"        const sy = liveCanvas.height;\n"
"        const x1 = d.box[0] * sx;\n"
"        const y1 = d.box[1] * sy;\n"
"        const x2 = d.box[2] * sx;\n"
"        const y2 = d.box[3] * sy;\n"
"        const w = x2 - x1;\n"
"        const h = y2 - y1;\n"
"        const color = CLASS_COLORS[idx % CLASS_COLORS.length];\n"
"\n"
"        ctx.strokeStyle = color.border;\n"
"        ctx.lineWidth = 2.5;\n"
"        ctx.strokeRect(x1, y1, w, h);\n"
"\n"
"        ctx.fillStyle = color.bg;\n"
"        ctx.fillRect(x1, y1, w, h);\n"
"\n"
"        // Tag label\n"
"        const label = `${d.class} ${(d.confidence * 100).toFixed(0)}%`;\n"
"        ctx.font = '600 13px Outfit, sans-serif';\n"
"        const textWidth = ctx.measureText(label).width;\n"
"\n"
"        ctx.fillStyle = color.border;\n"
"        ctx.fillRect(x1, y1 > 22 ? y1 - 22 : y1, textWidth + 10, 20);\n"
"\n"
"        ctx.fillStyle = '#040914';\n"
"        ctx.fillText(label, x1 + 5, y1 > 22 ? y1 - 7 : y1 + 14);\n"
"      });\n"
"\n"
"      // 4. Update Telemetry UI\n"
"      if (meta.visorc_ms !== undefined) {\n"
"        document.getElementById('statVisorcMs').innerText = `${meta.visorc_ms.toFixed(2)} ms`;\n"
"      }\n"
"      if (meta.total_ms !== undefined) {\n"
"        document.getElementById('statTotalMs').innerText = `${meta.total_ms.toFixed(2)} ms`;\n"
"      }\n"
"      if (meta.fps !== undefined) {\n"
"        document.getElementById('statFps').innerText = `${meta.fps.toFixed(1)} FPS`;\n"
"      }\n"
"      document.getElementById('statCount').innerText = dets.length;\n"
"\n"
"      // Update Detection Sidebar\n"
"      if (dets.length > 0) {\n"
"        detList.innerHTML = '';\n"
"        dets.forEach((d, idx) => {\n"
"          const color = CLASS_COLORS[idx % CLASS_COLORS.length];\n"
"          const item = document.createElement('div');\n"
"          item.className = 'det-item';\n"
"          item.innerHTML = `<span style=\"font-weight:600; color:#fff;\">${d.class}</span>` +\n"
"                           `<span class=\"det-tag\" style=\"background:${color.bg}; color:${color.border};\">${(d.confidence * 100).toFixed(1)}%</span>`;\n"
"          detList.appendChild(item);\n"
"        });\n"
"      } else {\n"
"        detList.innerHTML = '<div style=\"text-align: center; color: var(--text-sub); font-size: 0.85rem; padding: 1rem;\">No detections matching filter</div>';\n"
"      }\n"
"    }\n"
"\n"
"    // Photo Upload Handlers\n"
"    let activeFile = null;\n"
"    uploadZone.onclick = () => fileInput.click();\n"
"    uploadZone.ondragover = (e) => { e.preventDefault(); uploadZone.classList.add('dragover'); };\n"
"    uploadZone.ondragleave = () => uploadZone.classList.remove('dragover');\n"
"    uploadZone.ondrop = (e) => {\n"
"      e.preventDefault();\n"
"      uploadZone.classList.remove('dragover');\n"
"      if (e.dataTransfer.files.length) handleFile(e.dataTransfer.files[0]);\n"
"    };\n"
"    fileInput.onchange = () => {\n"
"      if (fileInput.files.length) handleFile(fileInput.files[0]);\n"
"    };\n"
"\n"
"    function handleFile(f) {\n"
"      activeFile = f;\n"
"      const r = new FileReader();\n"
"      r.onload = (e) => {\n"
"        loadedImage = new Image();\n"
"        loadedImage.onload = () => {\n"
"          uploadCanvas.width = loadedImage.naturalWidth;\n"
"          uploadCanvas.height = loadedImage.naturalHeight;\n"
"          uploadCtx.drawImage(loadedImage, 0, 0);\n"
"          uploadCanvas.style.display = 'block';\n"
"        };\n"
"        loadedImage.src = e.target.result;\n"
"      };\n"
"      r.readAsDataURL(f);\n"
"    }\n"
"\n"
"    inferBtn.onclick = async () => {\n"
"      if (!activeFile) {\n"
"        alert('Please select or drop an image first');\n"
"        return;\n"
"      }\n"
"      inferBtn.disabled = true;\n"
"      inferBtn.innerText = 'Processing on VisORC...';\n"
"      try {\n"
"        const res = await fetch(`/infer?thresh=${currentConf}&nms=${currentNms}`, {\n"
"          method: 'POST',\n"
"          body: activeFile\n"
"        });\n"
"        const json = await res.json();\n"
"        if (loadedImage) {\n"
"          uploadCanvas.width = loadedImage.naturalWidth;\n"
"          uploadCanvas.height = loadedImage.naturalHeight;\n"
"          uploadCtx.drawImage(loadedImage, 0, 0);\n"
"          if (json.detections && json.detections.length > 0) {\n"
"            const cw = uploadCanvas.width;\n"
"            const ch = uploadCanvas.height;\n"
"            json.detections.forEach((d, idx) => {\n"
"              const color = CLASS_COLORS[idx % CLASS_COLORS.length];\n"
"              const bx1 = d.box[0] * cw;\n"
"              const by1 = d.box[1] * ch;\n"
"              const bx2 = d.box[2] * cw;\n"
"              const by2 = d.box[3] * ch;\n"
"              const bw = bx2 - bx1;\n"
"              const bh = by2 - by1;\n"
"              uploadCtx.strokeStyle = color.border;\n"
"              uploadCtx.lineWidth = Math.max(2, Math.round(cw / 320));\n"
"              uploadCtx.strokeRect(bx1, by1, bw, bh);\n"
"              const fontSize = Math.max(12, Math.round(cw / 45));\n"
"              uploadCtx.font = `600 ${fontSize}px Inter, sans-serif`;\n"
"              const label = `${d.class} ${(d.confidence * 100).toFixed(1)}%`;\n"
"              const tw = uploadCtx.measureText(label).width;\n"
"              uploadCtx.fillStyle = color.border;\n"
"              uploadCtx.fillRect(bx1, Math.max(0, by1 - fontSize - 6), tw + 8, fontSize + 6);\n"
"              uploadCtx.fillStyle = '#ffffff';\n"
"              uploadCtx.fillText(label, bx1 + 4, Math.max(fontSize, by1 - 4));\n"
"            });\n"
"          }\n"
"        }\n"
"        document.getElementById('statVisorcMs').innerText = json.visorc_time_ms ? `${json.visorc_time_ms.toFixed(2)} ms` : '--';\n"
"        document.getElementById('statTotalMs').innerText = json.total_time_ms ? `${json.total_time_ms.toFixed(2)} ms` : '--';\n"
"        document.getElementById('statFps').innerText = json.total_time_ms ? `${(1000.0 / json.total_time_ms).toFixed(1)} FPS` : '--';\n"
"        document.getElementById('statCount').innerText = json.detections ? json.detections.length : 0;\n"
"        if (json.detections && json.detections.length > 0) {\n"
"          detList.innerHTML = '';\n"
"          json.detections.forEach((d, idx) => {\n"
"            const color = CLASS_COLORS[idx % CLASS_COLORS.length];\n"
"            const item = document.createElement('div');\n"
"            item.className = 'det-item';\n"
"            item.innerHTML = `<span style=\"font-weight:600; color:#fff;\">${d.class}</span>` +\n"
"                             `<span class=\"det-tag\" style=\"background:${color.bg}; color:${color.border};\">${(d.confidence * 100).toFixed(1)}%</span>`;\n"
"            detList.appendChild(item);\n"
"          });\n"
"        }\n"
"      } catch (e) {\n"
"        alert('Inference failed: ' + e.message);\n"
"      } finally {\n"
"        inferBtn.disabled = false;\n"
"        inferBtn.innerText = 'Run VisORC Inference';\n"
"      }\n"
"    };\n"
"\n"
"    // System Info\n"
"    async function fetchInfo() {\n"
"      try {\n"
"        const res = await fetch('/api/info');\n"
"        const d = await res.json();\n"
"        document.getElementById('osBadgeText').innerText = `${d.pretty_name} (${d.machine})`;\n"
"      } catch (e) {\n"
"        document.getElementById('osBadgeText').innerText = 'Connected to Ambarella CVFlow';\n"
"      }\n"
"    }\n"
"\n"
"    fetchInfo();\n"
"    startStream();\n"
"  </script>\n"
"</body>\n"
"</html>\n"
;


#endif /* AMBA_VIRT_DASHBOARD_HTML_HXX */
