# Configuration for dhcpcd on QNX 8.0 HVM / EVE-OS
#
# Use the hardware address of the interface for the Client ID
# to ensure compatibility with MAC-keyed DHCP reservations in dnsmasq.
clientid

# Avoid RFC 4361 DUID mismatch with MAC-based static reservations
#duid

# Persist interface configuration when dhcpcd exits
#persistent

# Vendor class ID blank
vendorclassid

# A list of options to request from the DHCP server
option domain_name_servers, domain_name, domain_search
option classless_static_routes
option interface_mtu
option host_name

# Rapid commit support
option rapid_commit

# Require ServerID
require dhcp_server_identifier

# IPv6 SLAAC address generation
slaac private
