#!/bin/sh
# Stage the NOHYPER amba_virt module into the eve-kernel source tree so the
# EVE kernel image builds it alongside cavalry.
#
#   ./scripts/install_kmod_to_eve_kernel.sh
#   ./scripts/install_kmod_to_eve_kernel.sh --eve-kernel=/path/to/eve-kernel
#   ./scripts/install_kmod_to_eve_kernel.sh --check
#
# drivers/amba_virt is the source of truth. eve-kernel/ambarella/ is untracked in that
# repo (it is dropped in out-of-band, same as cavalry), so this has to be re-run
# after a fresh eve-kernel checkout and whenever the module sources change.
# Dockerfile.gcc builds whatever this script leaves behind.

set -eu

ROOT=$(CDPATH= cd -- "$(dirname "$0")/.." && pwd)
SRC="$ROOT/drivers/amba_virt"
EVE=${EVE:-$(CDPATH= cd -- "$ROOT/../eve" 2>/dev/null && pwd || true)}
EVE_KERNEL=${EVE_KERNEL:-${EVE:+$EVE/eve-kernel}}
CHECK=0

usage() {
	echo "usage: scripts/install_kmod_to_eve_kernel.sh [--eve-kernel=DIR] [--check]" >&2
}

while [ "$#" -gt 0 ]; do
	case "$1" in
	-h|--help)
		usage
		exit 0
		;;
	--check)
		CHECK=1
		shift
		;;
	--eve-kernel=*)
		EVE_KERNEL=${1#--eve-kernel=}
		shift
		;;
	--eve-kernel)
		if [ "$#" -lt 2 ]; then
			echo "install_kmod_to_eve_kernel.sh: --eve-kernel needs a path" >&2
			exit 1
		fi
		EVE_KERNEL=$2
		shift 2
		;;
	*)
		echo "install_kmod_to_eve_kernel.sh: unknown option: $1" >&2
		usage
		exit 1
		;;
	esac
done

if [ -z "${EVE_KERNEL:-}" ] || [ ! -f "$EVE_KERNEL/Makefile.eve" ]; then
	echo "install_kmod_to_eve_kernel.sh: not an eve-kernel tree: ${EVE_KERNEL:-<unset>}" >&2
	echo "Set EVE=/path/to/eve or pass --eve-kernel=DIR" >&2
	exit 1
fi

DEST="$EVE_KERNEL/ambarella/amba_virt"

# Only the NOHYPER (host) side belongs in eve-kernel. The HVM side is built
# against Ubuntu headers inside the guest and must never use eve-kernel.
copy() {
	src=$1
	dst=$2
	if [ "$CHECK" -eq 1 ]; then
		if ! cmp -s "$src" "$dst"; then
			echo "stale: $dst" >&2
			STALE=1
		fi
	else
		install -D -m 0644 "$src" "$dst"
	fi
}

STALE=0

if [ "$CHECK" -eq 0 ]; then
	mkdir -p "$DEST/include"
fi

copy "$SRC/amba_virt_nohyper.c" "$DEST/amba_virt_nohyper.c"
copy "$SRC/amba_virt_core.c"     "$DEST/amba_virt_core.c"
copy "$SRC/amba_virt_core.h"     "$DEST/amba_virt_core.h"
copy "$SRC/include/uapi/amba_virt.h" "$DEST/include/amba_virt.h"

KBUILD_CONTENT='# SPDX-License-Identifier: GPL-2.0
#
# Generated by amba-virt/scripts/install_kmod_to_eve_kernel.sh. Do not edit
# here; edit drivers/amba_virt in the amba-virt repo and re-run that script.

ccflags-y += -I$(src)/include

obj-m := amba_virt.o
amba_virt-y := amba_virt_nohyper.o amba_virt_core.o
'

if [ "$CHECK" -eq 1 ]; then
	# Both sides go through command substitution so trailing newlines are
	# stripped consistently.
	if [ ! -f "$DEST/Kbuild" ] || [ "$(cat "$DEST/Kbuild")" != "$(printf '%s' "$KBUILD_CONTENT")" ]; then
		echo "stale: $DEST/Kbuild" >&2
		STALE=1
	fi
	if [ "$STALE" -ne 0 ]; then
		echo "install_kmod_to_eve_kernel.sh: eve-kernel copy is out of date; re-run without --check" >&2
		exit 1
	fi
	echo "install_kmod_to_eve_kernel.sh: $DEST is up to date" >&2
	exit 0
fi

printf '%s' "$KBUILD_CONTENT" > "$DEST/Kbuild"

echo "install_kmod_to_eve_kernel.sh: staged into $DEST" >&2
